### ISSUE TITLE
Fichier readme

### ISSUE THREAD

**Issue by mahugnon** [DubusA/Sokoban#1]
Un bon projet informatique doit pouvoir s'expliquer tout seul aux visiteurs du projet. Ce que les gens font dans la pratique est qu'ils créent un fichier readme.md pour expliquer ce que le projet fait et comment l'utiliser. C'est aussi utile pour toi si tu reviens sur le projet longtemps après.

**Comment by DubusA** [comment]
Merci, j'ai ajouté le fichier README.md
